// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/purchase_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchasedTourResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty          int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags                []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price               float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId            int64                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	TotalDistance       float64                `protobuf:"fixed64,9,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	DurationByTransport map[string]int32       `protobuf:"bytes,10,rep,name=duration_by_transport,json=durationByTransport,proto3" json:"duration_by_transport,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PurchasedTourResponse) Reset() {
	*x = PurchasedTourResponse{}
	mi := &file_proto_purchase_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchasedTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasedTourResponse) ProtoMessage() {}

func (x *PurchasedTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasedTourResponse.ProtoReflect.Descriptor instead.
func (*PurchasedTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{0}
}

func (x *PurchasedTourResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PurchasedTourResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PurchasedTourResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PurchasedTourResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *PurchasedTourResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PurchasedTourResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PurchasedTourResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PurchasedTourResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PurchasedTourResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *PurchasedTourResponse) GetDurationByTransport() map[string]int32 {
	if x != nil {
		return x.DurationByTransport
	}
	return nil
}

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        int64                  `protobuf:"varint,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_proto_purchase_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddToCartRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *AddToCartRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        int64                  `protobuf:"varint,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_proto_purchase_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFromCartRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *RemoveFromCartRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_proto_purchase_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckoutRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int64                  `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_purchase_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItem) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *OrderItem) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_proto_purchase_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{5}
}

func (x *CartResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []string               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_purchase_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckoutResponse) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_proto_purchase_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetCartRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type GetToursForTouristRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursForTouristRequest) Reset() {
	*x = GetToursForTouristRequest{}
	mi := &file_proto_purchase_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursForTouristRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursForTouristRequest) ProtoMessage() {}

func (x *GetToursForTouristRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursForTouristRequest.ProtoReflect.Descriptor instead.
func (*GetToursForTouristRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetToursForTouristRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type TouristToursResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tours         []*PurchasedTourResponse `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouristToursResponse) Reset() {
	*x = TouristToursResponse{}
	mi := &file_proto_purchase_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouristToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouristToursResponse) ProtoMessage() {}

func (x *TouristToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouristToursResponse.ProtoReflect.Descriptor instead.
func (*TouristToursResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{9}
}

func (x *TouristToursResponse) GetTours() []*PurchasedTourResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type IsTourPurchasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        int64                  `protobuf:"varint,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTourPurchasedRequest) Reset() {
	*x = IsTourPurchasedRequest{}
	mi := &file_proto_purchase_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTourPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTourPurchasedRequest) ProtoMessage() {}

func (x *IsTourPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTourPurchasedRequest.ProtoReflect.Descriptor instead.
func (*IsTourPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{10}
}

func (x *IsTourPurchasedRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *IsTourPurchasedRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type IsTourPurchasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPurchased   bool                   `protobuf:"varint,1,opt,name=is_purchased,json=isPurchased,proto3" json:"is_purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTourPurchasedResponse) Reset() {
	*x = IsTourPurchasedResponse{}
	mi := &file_proto_purchase_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTourPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTourPurchasedResponse) ProtoMessage() {}

func (x *IsTourPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTourPurchasedResponse.ProtoReflect.Descriptor instead.
func (*IsTourPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_service_proto_rawDescGZIP(), []int{11}
}

func (x *IsTourPurchasedResponse) GetIsPurchased() bool {
	if x != nil {
		return x.IsPurchased
	}
	return false
}

var File_proto_purchase_service_proto protoreflect.FileDescriptor

const file_proto_purchase_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/purchase_service.proto\"\xb0\x03\n" +
	"\x15PurchasedTourResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x03R\bauthorId\x12%\n" +
	"\x0etotal_distance\x18\t \x01(\x01R\rtotalDistance\x12c\n" +
	"\x15duration_by_transport\x18\n" +
	" \x03(\v2/.PurchasedTourResponse.DurationByTransportEntryR\x13durationByTransport\x1aF\n" +
	"\x18DurationByTransportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"J\n" +
	"\x10AddToCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\x03R\x06tourId\"O\n" +
	"\x15RemoveFromCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\x03R\x06tourId\"0\n" +
	"\x0fCheckoutRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\"W\n" +
	"\tOrderItem\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\x03R\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"Q\n" +
	"\fCartResponse\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".OrderItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice\"*\n" +
	"\x10CheckoutResponse\x12\x16\n" +
	"\x06tokens\x18\x01 \x03(\tR\x06tokens\"/\n" +
	"\x0eGetCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\":\n" +
	"\x19GetToursForTouristRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\"D\n" +
	"\x14TouristToursResponse\x12,\n" +
	"\x05tours\x18\x01 \x03(\v2\x16.PurchasedTourResponseR\x05tours\"P\n" +
	"\x16IsTourPurchasedRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\x03R\x06tourId\"<\n" +
	"\x17IsTourPurchasedResponse\x12!\n" +
	"\fis_purchased\x18\x01 \x01(\bR\visPurchased2\xe4\x02\n" +
	"\x0fPurchaseService\x12-\n" +
	"\tAddToCart\x12\x11.AddToCartRequest\x1a\r.CartResponse\x127\n" +
	"\x0eRemoveFromCart\x12\x16.RemoveFromCartRequest\x1a\r.CartResponse\x12/\n" +
	"\bCheckout\x12\x10.CheckoutRequest\x1a\x11.CheckoutResponse\x12)\n" +
	"\aGetCart\x12\x0f.GetCartRequest\x1a\r.CartResponse\x12G\n" +
	"\x12GetToursForTourist\x12\x1a.GetToursForTouristRequest\x1a\x15.TouristToursResponse\x12D\n" +
	"\x0fIsTourPurchased\x12\x17.IsTourPurchasedRequest\x1a\x18.IsTourPurchasedResponseBE\n" +
	"\"com.example.purchase_service.protoB\x14PurchaseServiceProtoP\x01Z\a./protob\x06proto3"

var (
	file_proto_purchase_service_proto_rawDescOnce sync.Once
	file_proto_purchase_service_proto_rawDescData []byte
)

func file_proto_purchase_service_proto_rawDescGZIP() []byte {
	file_proto_purchase_service_proto_rawDescOnce.Do(func() {
		file_proto_purchase_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_service_proto_rawDesc), len(file_proto_purchase_service_proto_rawDesc)))
	})
	return file_proto_purchase_service_proto_rawDescData
}

var file_proto_purchase_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_purchase_service_proto_goTypes = []any{
	(*PurchasedTourResponse)(nil),     // 0: PurchasedTourResponse
	(*AddToCartRequest)(nil),          // 1: AddToCartRequest
	(*RemoveFromCartRequest)(nil),     // 2: RemoveFromCartRequest
	(*CheckoutRequest)(nil),           // 3: CheckoutRequest
	(*OrderItem)(nil),                 // 4: OrderItem
	(*CartResponse)(nil),              // 5: CartResponse
	(*CheckoutResponse)(nil),          // 6: CheckoutResponse
	(*GetCartRequest)(nil),            // 7: GetCartRequest
	(*GetToursForTouristRequest)(nil), // 8: GetToursForTouristRequest
	(*TouristToursResponse)(nil),      // 9: TouristToursResponse
	(*IsTourPurchasedRequest)(nil),    // 10: IsTourPurchasedRequest
	(*IsTourPurchasedResponse)(nil),   // 11: IsTourPurchasedResponse
	nil,                               // 12: PurchasedTourResponse.DurationByTransportEntry
}
var file_proto_purchase_service_proto_depIdxs = []int32{
	12, // 0: PurchasedTourResponse.duration_by_transport:type_name -> PurchasedTourResponse.DurationByTransportEntry
	4,  // 1: CartResponse.items:type_name -> OrderItem
	0,  // 2: TouristToursResponse.tours:type_name -> PurchasedTourResponse
	1,  // 3: PurchaseService.AddToCart:input_type -> AddToCartRequest
	2,  // 4: PurchaseService.RemoveFromCart:input_type -> RemoveFromCartRequest
	3,  // 5: PurchaseService.Checkout:input_type -> CheckoutRequest
	7,  // 6: PurchaseService.GetCart:input_type -> GetCartRequest
	8,  // 7: PurchaseService.GetToursForTourist:input_type -> GetToursForTouristRequest
	10, // 8: PurchaseService.IsTourPurchased:input_type -> IsTourPurchasedRequest
	5,  // 9: PurchaseService.AddToCart:output_type -> CartResponse
	5,  // 10: PurchaseService.RemoveFromCart:output_type -> CartResponse
	6,  // 11: PurchaseService.Checkout:output_type -> CheckoutResponse
	5,  // 12: PurchaseService.GetCart:output_type -> CartResponse
	9,  // 13: PurchaseService.GetToursForTourist:output_type -> TouristToursResponse
	11, // 14: PurchaseService.IsTourPurchased:output_type -> IsTourPurchasedResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_purchase_service_proto_init() }
func file_proto_purchase_service_proto_init() {
	if File_proto_purchase_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_service_proto_rawDesc), len(file_proto_purchase_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_service_proto_goTypes,
		DependencyIndexes: file_proto_purchase_service_proto_depIdxs,
		MessageInfos:      file_proto_purchase_service_proto_msgTypes,
	}.Build()
	File_proto_purchase_service_proto = out.File
	file_proto_purchase_service_proto_goTypes = nil
	file_proto_purchase_service_proto_depIdxs = nil
}
