// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/tour_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourService_GetTourById_FullMethodName   = "/TourService/GetTourById"
	TourService_CreateTour_FullMethodName    = "/TourService/CreateTour"
	TourService_GetToursByIds_FullMethodName = "/TourService/GetToursByIds"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourResponse, error)
	CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*CreateTourResponse, error)
	GetToursByIds(ctx context.Context, in *GetToursByIdsRequest, opts ...grpc.CallOption) (*ToursListResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_GetTourById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*CreateTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTourResponse)
	err := c.cc.Invoke(ctx, TourService_CreateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetToursByIds(ctx context.Context, in *GetToursByIdsRequest, opts ...grpc.CallOption) (*ToursListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToursListResponse)
	err := c.cc.Invoke(ctx, TourService_GetToursByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility.
type TourServiceServer interface {
	GetTourById(context.Context, *GetTourByIdRequest) (*TourResponse, error)
	CreateTour(context.Context, *CreateTourRequest) (*CreateTourResponse, error)
	GetToursByIds(context.Context, *GetToursByIdsRequest) (*ToursListResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourServiceServer struct{}

func (UnimplementedTourServiceServer) GetTourById(context.Context, *GetTourByIdRequest) (*TourResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedTourServiceServer) CreateTour(context.Context, *CreateTourRequest) (*CreateTourResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourServiceServer) GetToursByIds(context.Context, *GetToursByIdsRequest) (*ToursListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToursByIds not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}
func (UnimplementedTourServiceServer) testEmbeddedByValue()                     {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	// If the following call panics, it indicates UnimplementedTourServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourById(ctx, req.(*GetTourByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTour(ctx, req.(*CreateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetToursByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToursByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetToursByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetToursByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetToursByIds(ctx, req.(*GetToursByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTourById",
			Handler:    _TourService_GetTourById_Handler,
		},
		{
			MethodName: "CreateTour",
			Handler:    _TourService_CreateTour_Handler,
		},
		{
			MethodName: "GetToursByIds",
			Handler:    _TourService_GetToursByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}

const (
	TourExecutionService_CheckPosition_FullMethodName = "/TourExecutionService/CheckPosition"
)

// TourExecutionServiceClient is the client API for TourExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourExecutionServiceClient interface {
	CheckPosition(ctx context.Context, in *CheckPositionRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
}

type tourExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourExecutionServiceClient(cc grpc.ClientConnInterface) TourExecutionServiceClient {
	return &tourExecutionServiceClient{cc}
}

func (c *tourExecutionServiceClient) CheckPosition(ctx context.Context, in *CheckPositionRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourExecutionService_CheckPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourExecutionServiceServer is the server API for TourExecutionService service.
// All implementations must embed UnimplementedTourExecutionServiceServer
// for forward compatibility.
type TourExecutionServiceServer interface {
	CheckPosition(context.Context, *CheckPositionRequest) (*TourExecutionResponse, error)
	mustEmbedUnimplementedTourExecutionServiceServer()
}

// UnimplementedTourExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourExecutionServiceServer struct{}

func (UnimplementedTourExecutionServiceServer) CheckPosition(context.Context, *CheckPositionRequest) (*TourExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPosition not implemented")
}
func (UnimplementedTourExecutionServiceServer) mustEmbedUnimplementedTourExecutionServiceServer() {}
func (UnimplementedTourExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeTourExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourExecutionServiceServer will
// result in compilation errors.
type UnsafeTourExecutionServiceServer interface {
	mustEmbedUnimplementedTourExecutionServiceServer()
}

func RegisterTourExecutionServiceServer(s grpc.ServiceRegistrar, srv TourExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedTourExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourExecutionService_ServiceDesc, srv)
}

func _TourExecutionService_CheckPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourExecutionServiceServer).CheckPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourExecutionService_CheckPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourExecutionServiceServer).CheckPosition(ctx, req.(*CheckPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourExecutionService_ServiceDesc is the grpc.ServiceDesc for TourExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TourExecutionService",
	HandlerType: (*TourExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPosition",
			Handler:    _TourExecutionService_CheckPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}
