// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/tour_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_proto_tour_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTourByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    int32                  `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      int64                  `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_proto_tour_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type TourResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty          int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags                []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price               float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId            int64                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	TotalDistance       float64                `protobuf:"fixed64,9,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	DurationByTransport map[string]int32       `protobuf:"bytes,10,rep,name=duration_by_transport,json=durationByTransport,proto3" json:"duration_by_transport,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_proto_tour_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *TourResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *TourResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TourResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *TourResponse) GetDurationByTransport() map[string]int32 {
	if x != nil {
		return x.DurationByTransport
	}
	return nil
}

type CreateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourResponse) Reset() {
	*x = CreateTourResponse{}
	mi := &file_proto_tour_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourResponse) ProtoMessage() {}

func (x *CreateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourResponse.ProtoReflect.Descriptor instead.
func (*CreateTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetToursByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByIdsRequest) Reset() {
	*x = GetToursByIdsRequest{}
	mi := &file_proto_tour_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByIdsRequest) ProtoMessage() {}

func (x *GetToursByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetToursByIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetToursByIdsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ToursListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourResponse        `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToursListResponse) Reset() {
	*x = ToursListResponse{}
	mi := &file_proto_tour_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToursListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToursListResponse) ProtoMessage() {}

func (x *ToursListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToursListResponse.ProtoReflect.Descriptor instead.
func (*ToursListResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{5}
}

func (x *ToursListResponse) GetTours() []*TourResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type CheckPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   int64                  `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPositionRequest) Reset() {
	*x = CheckPositionRequest{}
	mi := &file_proto_tour_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPositionRequest) ProtoMessage() {}

func (x *CheckPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPositionRequest.ProtoReflect.Descriptor instead.
func (*CheckPositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPositionRequest) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *CheckPositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CheckPositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type TourExecutionResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId                int64                  `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TouristId                  int64                  `protobuf:"varint,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId                     int64                  `protobuf:"varint,3,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Status                     string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartTime                  string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                    string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LastActivityDateTime       string                 `protobuf:"bytes,7,opt,name=last_activity_date_time,json=lastActivityDateTime,proto3" json:"last_activity_date_time,omitempty"`
	LastLatitude               float64                `protobuf:"fixed64,8,opt,name=last_latitude,json=lastLatitude,proto3" json:"last_latitude,omitempty"`
	LastLongitude              float64                `protobuf:"fixed64,9,opt,name=last_longitude,json=lastLongitude,proto3" json:"last_longitude,omitempty"`
	CompletedKeyPointsWithTime map[int64]string       `protobuf:"bytes,10,rep,name=completed_key_points_with_time,json=completedKeyPointsWithTime,proto3" json:"completed_key_points_with_time,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TourExecutionResponse) Reset() {
	*x = TourExecutionResponse{}
	mi := &file_proto_tour_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecutionResponse) ProtoMessage() {}

func (x *TourExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecutionResponse.ProtoReflect.Descriptor instead.
func (*TourExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{7}
}

func (x *TourExecutionResponse) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *TourExecutionResponse) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *TourExecutionResponse) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *TourExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecutionResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TourExecutionResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TourExecutionResponse) GetLastActivityDateTime() string {
	if x != nil {
		return x.LastActivityDateTime
	}
	return ""
}

func (x *TourExecutionResponse) GetLastLatitude() float64 {
	if x != nil {
		return x.LastLatitude
	}
	return 0
}

func (x *TourExecutionResponse) GetLastLongitude() float64 {
	if x != nil {
		return x.LastLongitude
	}
	return 0
}

func (x *TourExecutionResponse) GetCompletedKeyPointsWithTime() map[int64]string {
	if x != nil {
		return x.CompletedKeyPointsWithTime
	}
	return nil
}

var File_proto_tour_service_proto protoreflect.FileDescriptor

const file_proto_tour_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/tour_service.proto\"$\n" +
	"\x12GetTourByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9a\x01\n" +
	"\x11CreateTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x05R\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\x03R\bauthorId\"\x9e\x03\n" +
	"\fTourResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x03R\bauthorId\x12%\n" +
	"\x0etotal_distance\x18\t \x01(\x01R\rtotalDistance\x12Z\n" +
	"\x15duration_by_transport\x18\n" +
	" \x03(\v2&.TourResponse.DurationByTransportEntryR\x13durationByTransport\x1aF\n" +
	"\x18DurationByTransportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\".\n" +
	"\x12CreateTourResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x14GetToursByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"8\n" +
	"\x11ToursListResponse\x12#\n" +
	"\x05tours\x18\x01 \x03(\v2\r.TourResponseR\x05tours\"s\n" +
	"\x14CheckPositionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x03R\vexecutionId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\x92\x04\n" +
	"\x15TourExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x03R\vexecutionId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\x03R\ttouristId\x12\x17\n" +
	"\atour_id\x18\x03 \x01(\x03R\x06tourId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x125\n" +
	"\x17last_activity_date_time\x18\a \x01(\tR\x14lastActivityDateTime\x12#\n" +
	"\rlast_latitude\x18\b \x01(\x01R\flastLatitude\x12%\n" +
	"\x0elast_longitude\x18\t \x01(\x01R\rlastLongitude\x12z\n" +
	"\x1ecompleted_key_points_with_time\x18\n" +
	" \x03(\v26.TourExecutionResponse.CompletedKeyPointsWithTimeEntryR\x1acompletedKeyPointsWithTime\x1aM\n" +
	"\x1fCompletedKeyPointsWithTimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb3\x01\n" +
	"\vTourService\x121\n" +
	"\vGetTourById\x12\x13.GetTourByIdRequest\x1a\r.TourResponse\x125\n" +
	"\n" +
	"CreateTour\x12\x12.CreateTourRequest\x1a\x13.CreateTourResponse\x12:\n" +
	"\rGetToursByIds\x12\x15.GetToursByIdsRequest\x1a\x12.ToursListResponse2V\n" +
	"\x14TourExecutionService\x12>\n" +
	"\rCheckPosition\x12\x15.CheckPositionRequest\x1a\x16.TourExecutionResponseB=\n" +
	"\x1ecom.example.tour_service.protoB\x10TourServiceProtoP\x01Z\a./protob\x06proto3"

var (
	file_proto_tour_service_proto_rawDescOnce sync.Once
	file_proto_tour_service_proto_rawDescData []byte
)

func file_proto_tour_service_proto_rawDescGZIP() []byte {
	file_proto_tour_service_proto_rawDescOnce.Do(func() {
		file_proto_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_service_proto_rawDesc), len(file_proto_tour_service_proto_rawDesc)))
	})
	return file_proto_tour_service_proto_rawDescData
}

var file_proto_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_tour_service_proto_goTypes = []any{
	(*GetTourByIdRequest)(nil),    // 0: GetTourByIdRequest
	(*CreateTourRequest)(nil),     // 1: CreateTourRequest
	(*TourResponse)(nil),          // 2: TourResponse
	(*CreateTourResponse)(nil),    // 3: CreateTourResponse
	(*GetToursByIdsRequest)(nil),  // 4: GetToursByIdsRequest
	(*ToursListResponse)(nil),     // 5: ToursListResponse
	(*CheckPositionRequest)(nil),  // 6: CheckPositionRequest
	(*TourExecutionResponse)(nil), // 7: TourExecutionResponse
	nil,                           // 8: TourResponse.DurationByTransportEntry
	nil,                           // 9: TourExecutionResponse.CompletedKeyPointsWithTimeEntry
}
var file_proto_tour_service_proto_depIdxs = []int32{
	8, // 0: TourResponse.duration_by_transport:type_name -> TourResponse.DurationByTransportEntry
	2, // 1: ToursListResponse.tours:type_name -> TourResponse
	9, // 2: TourExecutionResponse.completed_key_points_with_time:type_name -> TourExecutionResponse.CompletedKeyPointsWithTimeEntry
	0, // 3: TourService.GetTourById:input_type -> GetTourByIdRequest
	1, // 4: TourService.CreateTour:input_type -> CreateTourRequest
	4, // 5: TourService.GetToursByIds:input_type -> GetToursByIdsRequest
	6, // 6: TourExecutionService.CheckPosition:input_type -> CheckPositionRequest
	2, // 7: TourService.GetTourById:output_type -> TourResponse
	3, // 8: TourService.CreateTour:output_type -> CreateTourResponse
	5, // 9: TourService.GetToursByIds:output_type -> ToursListResponse
	7, // 10: TourExecutionService.CheckPosition:output_type -> TourExecutionResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_tour_service_proto_init() }
func file_proto_tour_service_proto_init() {
	if File_proto_tour_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_service_proto_rawDesc), len(file_proto_tour_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_tour_service_proto_goTypes,
		DependencyIndexes: file_proto_tour_service_proto_depIdxs,
		MessageInfos:      file_proto_tour_service_proto_msgTypes,
	}.Build()
	File_proto_tour_service_proto = out.File
	file_proto_tour_service_proto_goTypes = nil
	file_proto_tour_service_proto_depIdxs = nil
}
