// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/tour_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_proto_tour_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTourByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    int32                  `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      int64                  `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_proto_tour_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId      int64                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	TotalDistance float64                `protobuf:"fixed64,9,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_proto_tour_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *TourResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *TourResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TourResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

type CreateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourResponse) Reset() {
	*x = CreateTourResponse{}
	mi := &file_proto_tour_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourResponse) ProtoMessage() {}

func (x *CreateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourResponse.ProtoReflect.Descriptor instead.
func (*CreateTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_tour_service_proto protoreflect.FileDescriptor

const file_proto_tour_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/tour_service.proto\"$\n" +
	"\x12GetTourByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9a\x01\n" +
	"\x11CreateTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x05R\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\x03R\bauthorId\"\xfa\x01\n" +
	"\fTourResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x03R\bauthorId\x12%\n" +
	"\x0etotal_distance\x18\t \x01(\x01R\rtotalDistance\".\n" +
	"\x12CreateTourResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2w\n" +
	"\vTourService\x121\n" +
	"\vGetTourById\x12\x13.GetTourByIdRequest\x1a\r.TourResponse\x125\n" +
	"\n" +
	"CreateTour\x12\x12.CreateTourRequest\x1a\x13.CreateTourResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_tour_service_proto_rawDescOnce sync.Once
	file_proto_tour_service_proto_rawDescData []byte
)

func file_proto_tour_service_proto_rawDescGZIP() []byte {
	file_proto_tour_service_proto_rawDescOnce.Do(func() {
		file_proto_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_service_proto_rawDesc), len(file_proto_tour_service_proto_rawDesc)))
	})
	return file_proto_tour_service_proto_rawDescData
}

var file_proto_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tour_service_proto_goTypes = []any{
	(*GetTourByIdRequest)(nil), // 0: GetTourByIdRequest
	(*CreateTourRequest)(nil),  // 1: CreateTourRequest
	(*TourResponse)(nil),       // 2: TourResponse
	(*CreateTourResponse)(nil), // 3: CreateTourResponse
}
var file_proto_tour_service_proto_depIdxs = []int32{
	0, // 0: TourService.GetTourById:input_type -> GetTourByIdRequest
	1, // 1: TourService.CreateTour:input_type -> CreateTourRequest
	2, // 2: TourService.GetTourById:output_type -> TourResponse
	3, // 3: TourService.CreateTour:output_type -> CreateTourResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tour_service_proto_init() }
func file_proto_tour_service_proto_init() {
	if File_proto_tour_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_service_proto_rawDesc), len(file_proto_tour_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tour_service_proto_goTypes,
		DependencyIndexes: file_proto_tour_service_proto_depIdxs,
		MessageInfos:      file_proto_tour_service_proto_msgTypes,
	}.Build()
	File_proto_tour_service_proto = out.File
	file_proto_tour_service_proto_goTypes = nil
	file_proto_tour_service_proto_depIdxs = nil
}
