spring.application.name=purchase_service
server.port=8083

spring.mongodb.uri=mongodb://mongo:27017/purchase_db

grpc.server.port=9093

grpc.client.tour-service.address=static://tour-service:9090
grpc.client.tour-service.negotiation-type=plaintext
tour.grpc.host=tour-service
tour.grpc.port=9090