spring.application.name=stakeholders_service

spring.datasource.url=jdbc:postgresql://localhost:5432/stakeholders
spring.datasource.username=postgres
spring.datasource.password=ftn
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
tour.service.url=${TOUR_SERVICE_URL:http://localhost:8085}