INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_TOURIST') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_GUIDE') ON CONFLICT (name) DO NOTHING;
