-- 1. ULOGE
INSERT INTO roles (id, name)
SELECT 1, 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 1);

INSERT INTO roles (id, name)
SELECT 2, 'ROLE_TOURIST' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 2);

INSERT INTO roles (id, name)
SELECT 3, 'ROLE_GUIDE' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 3);


